COPT  = -ansi -Wall -pedantic -O3
LINK1 = 
LINK2 =
CC    = cc

OFILES = hsubgroup.o sophie.o
LFILES = bioplib/ReadPIR.o bioplib/OpenStdFiles.o

hsubgroup : $(OFILES) $(LFILES)
	$(CC) -o hsubgroup $(OFILES) $(LFILES) -lm $(LINK2)
   
.c.o :
	$(CC) $(COPT) -o $@ -c $<

clean :
	/bin/rm $(OFILES) $(LFILES)


